### ISSUE TITLE
Unicode character support in grammar

### ISSUE THREAD

**Issue by hiteshsharma** [javacc/javacc#216]
Hi, I'm using JavaCC 7.0.10 and JJTree to define a grammar but I see that javacc is not able to understand unicode characters in the grammar
```
TOKEN: {
  <SPACE: [" ", "\u000A", "\t", "\f" ]>
}
```
When generating the parser I'm getting the following error
```
Java Compiler Compiler Version 7.0.10 (Tree Builder)
(type "jjtree" with no arguments for help)
Reading from file content.jjt . . .
Exception in thread "main" org.javacc.jjtree.TokenMgrError: Lexical error at line 203, column 19.  Encountered: "\n" (10), after : "\""
        at org.javacc.jjtree.JJTreeParserTokenManager.getNextToken(JJTreeParserTokenManager.java:2369)
        at org.javacc.jjtree.JJTreeParser.getToken(JJTreeParser.java:9492)
        at org.javacc.jjtree.JJTreeParser.jjtreeOpenNodeScope(JJTreeParser.java:8)
        at org.javacc.jjtree.JJTreeParser.character_descriptor(JJTreeParser.java:2025)
        at org.javacc.jjtree.JJTreeParser.character_list(JJTreeParser.java:1990)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression_unit(JJTreeParser.java:1852)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression(JJTreeParser.java:1753)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression_choices(JJTreeParser.java:1708)
        at org.javacc.jjtree.JJTreeParser.regular_expression(JJTreeParser.java:1623)
        at org.javacc.jjtree.JJTreeParser.regexpr_spec(JJTreeParser.java:958)
        at org.javacc.jjtree.JJTreeParser.regular_expr_production(JJTreeParser.java:861)
        at org.javacc.jjtree.JJTreeParser.production(JJTreeParser.java:320)
        at org.javacc.jjtree.JJTreeParser.javacc_input(JJTreeParser.java:107)
        at org.javacc.jjtree.JJTree.main(JJTree.java:164)
        at org.javacc.jjtree.Main.main(Main.java:40)
```

Any suggestions? Thanks in advance!

**Comment by new-javacc** [comment]
Just escape the backslashOn Sep 29, 2021 6:54 PM, hitesh sharma ***@***.***> wrote:
Hi, I'm using JavaCC 7.0.10 and JJTree to define a grammar but I see that javacc is not able to understand unicode characters in the grammar
TOKEN: {
  <SPACE: [" ", "\u000A", "\t", "\f" ]>
}

When generating the parser I'm getting the following error
Java Compiler Compiler Version 7.0.10 (Tree Builder)
(type "jjtree" with no arguments for help)
Reading from file content.jjt . . .
Exception in thread "main" org.javacc.jjtree.TokenMgrError: Lexical error at line 203, column 19.  Encountered: "\n" (10), after : "\""
        at org.javacc.jjtree.JJTreeParserTokenManager.getNextToken(JJTreeParserTokenManager.java:2369)
        at org.javacc.jjtree.JJTreeParser.getToken(JJTreeParser.java:9492)
        at org.javacc.jjtree.JJTreeParser.jjtreeOpenNodeScope(JJTreeParser.java:8)
        at org.javacc.jjtree.JJTreeParser.character_descriptor(JJTreeParser.java:2025)
        at org.javacc.jjtree.JJTreeParser.character_list(JJTreeParser.java:1990)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression_unit(JJTreeParser.java:1852)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression(JJTreeParser.java:1753)
        at org.javacc.jjtree.JJTreeParser.complex_regular_expression_choices(JJTreeParser.java:1708)
        at org.javacc.jjtree.JJTreeParser.regular_expression(JJTreeParser.java:1623)
        at org.javacc.jjtree.JJTreeParser.regexpr_spec(JJTreeParser.java:958)
        at org.javacc.jjtree.JJTreeParser.regular_expr_production(JJTreeParser.java:861)
        at org.javacc.jjtree.JJTreeParser.production(JJTreeParser.java:320)
        at org.javacc.jjtree.JJTreeParser.javacc_input(JJTreeParser.java:107)
        at org.javacc.jjtree.JJTree.main(JJTree.java:164)
        at org.javacc.jjtree.Main.main(Main.java:40)

Any suggestions? Thanks in advance!

**Comment by hiteshsharma** [comment]
Thanks. that gives the following error
```
Error parsing input: org.javacc.jjtree.ParseException: Encountered " "template" "template "" at line 298, column 5.
Was expecting one of:
    "LOOKAHEAD" ...
    "try" ...
    "(" ...
    "{" ...
    "[" ...
    "(" ...
    "(" ...
    "(" ...
    "LOOKAHEAD" ...
    "LOOKAHEAD" ...
    "(" ...
    "LOOKAHEAD" ...
    "LOOKAHEAD" ...
```

**Comment by hiteshsharma** [comment]
Actually I'm sorry, "template" is something that is defined in my grammar. Is template a reserved word in Javacc 7.0.10? It works fine with v6.1.2

**Comment by nineninesevenfour** [comment]
Hello @hiteshsharma 👋,

`"\u000A"` is the equivalent of `"\n"`, i'd recommend to use that instead.
### Background
JavaCC uses the option `JAVA_UNICODE_ESCAPE = true` in it's grammar. That means all occurrences of \u#### are replaced with their corresponding UTF-16 code unit prior to parsing the grammar, just like Java does when compiling source code.

When you enter `\u000A` in your grammar file it appears to the grammar parser as if you would have typed a newline, which causes the error. The same is true for `\u000D` (equivalent for `\r`) by the way.
For the same reason you cannot enter \u000A or \u000D in a Java string literal (see https://stackoverflow.com/questions/3866187/why-cant-i-use-u000d-and-u000a-as-cr-and-lf-in-java).

Escaping the backslash (`"\\u000A"`, as recommended before) would not lead to the expected result. 
Side note: If you prefer numeric specification you can use the octal notations `"\012"` for `"\n"` and `"\015"` for `"\r"` instead.

### Reserved Words
"template" is a reserved word for C++ code generation as is "typename":
```
/* C++ RESERVED WORDS AND LITERALS */

TOKEN :
{
  < TEMPLATE: "template" >
| < TYPENAME: "typename" >
}
```
You can refer to the docs:
https://javacc.github.io/javacc/documentation/bnf.html#reserved-words
and
https://javacc.github.io/javacc/documentation/bnf.html#reserved-and-literals

If that answers your question, please close the issue. 😊
