### ISSUE TITLE
Incorrect token returned by `jjtGetFirstToken()` method 

### ISSUE THREAD

**Issue by Toparvion** [javacc/javacc#292]
### Description

When generating parsers with `TRACK_TOKENS` option of `jjtree` tool, the first token of certain multi-token nodes is reported incorrectly by the `jjtGetFirstToken()` method – instead of pointing to the actual first node, it points to the last one, i.e. the same as `jjtGetLastToken()`.

### Steps to reproduce

1. Install JavaCC 7.0.13 (the latest one at the time of writing).

2. Download `ExpressionParser.jjt` grammar and `TestVisitor.java` class provided below.
   The grammar describes a simple language for arithmetic operations and function invocations. The visitor prints each node’s name and its first and last tokens separated by ellipsis (`...`) . The visitor is called from the `main` method declared right in the grammar.

3. Build and run the parser (assumed to be done with JDK 8+):

   ```shell
   jjtree ExpressionParser.jjt 
   javacc ExpressionParser.jj
   javac ExpressionParser.java 
   java ExpressionParser
   ```

   The parser should ask for the input from user. 

4. Type `1 + 2;` or any other simple arithmetic expression with at least two operands and hit Enter.

### Actual result

Output like:

```
Start: 1...;
 AddNode: 2...2
  LongConstNode: 1...1
  LongConstNode: 2...2
```

Note that for `AddNode` the first token is `2` which is **not** correct because the first token of the expression is `1`.

### Expected result

Output like:

```
Start: 1...;
 AddNode: 1...2
  LongConstNode: 1...1
  LongConstNode: 2...2
```

Note that for `AddNode` the first token is `1` which is correct.

### Additional info

When checked on the [Example 1](https://javacc.github.io/javacc/tutorials/examples.html#jjtree-example-1) from JavaCC documentation, which has similar grammar, the same visitor shows no errors. Therefore I suspect that the problem might be in the grammar itself, but since there is no errors nor warnings from the JavaCC, I cannot be sure. Would be glad to receive any help from the community.

### Attached files

<details>

<summary>ExpressionParser.jjt</summary>

```java
options {
  STATIC=false;
  MULTI=true;
  VISITOR=true;
  NODE_DEFAULT_VOID=true;
  UNICODE_INPUT=true;
  TRACK_TOKENS=true;
}

PARSER_BEGIN(ExpressionParser)

/**
 * An Expression Parser
 */
public class ExpressionParser {

  /** Main entry point */
  public static void main(String args[]) {
    System.out.println("Reading from standard input...");
    ExpressionParser parser = new ExpressionParser(System.in);
    try {
      SimpleNode root = parser.Start();
      TestVisitor visitor = new TestVisitor();
      root.jjtAccept(visitor, null);    
      
      System.out.println("Done.");
      
    } catch (Exception e) {
      System.out.println("Oops.");
      System.out.println(e.getMessage());
      e.printStackTrace();
    }
  }
}

PARSER_END(ExpressionParser)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
| <"/*" (~["*"])* "*" (~["/"] (~["*"])* "*")* "/">
}

MORE :
{
  "//" : IN_SINGLE_LINE_COMMENT
|
  "/*" : IN_MULTI_LINE_COMMENT
}

<IN_SINGLE_LINE_COMMENT>
SPECIAL_TOKEN : { <SINGLE_LINE_COMMENT:  (~["\r","\n","\u001a"])* ("\r"|"\n"|"\r\n")? > : DEFAULT }

<IN_MULTI_LINE_COMMENT>
SPECIAL_TOKEN :
{
  <MULTI_LINE_COMMENT: "*/" > : DEFAULT
}

<IN_SINGLE_LINE_COMMENT,IN_MULTI_LINE_COMMENT>
MORE :
{
  < ~[] >
}


TOKEN [IGNORE_CASE] :
{
  < OR: "||" >
|
  < AND: "&&" >
|
  < NOT: "!" >
|
  < BITWISE_OR: "|" >
|
  < BITWISE_XOR: "^" >
|
  < BITWISE_AND: "&" >
|
  < BITWISE_NOT: "~" >
|
  < TRUE: "TRUE" >
|
  < FALSE: "FALSE" >
|
  < NULL: "NULL" >
}

TOKEN : /* LITERALS */
{
  < INTEGER_LITERAL:
        <DECIMAL_LITERAL>
      | <HEX_LITERAL>
      | <OCTAL_LITERAL>
      | <BINARY_LITERAL>
  >
|
  < #HEX_LITERAL: "0" ["x","X"] (["0"-"9","a"-"f","A"-"F"])+ >
|
  < #DECIMAL_LITERAL: ["1"-"9"] (["0"-"9"])* >
|
  < #OCTAL_LITERAL: "0" (["0"-"7"])* >
|
  < #BINARY_LITERAL: "0" ["b","B"] (["0"-"1"])+ >
|
  < FLOATING_POINT_LITERAL:
      (["0"-"9"])+ "." (["0"-"9"])* (<EXPONENT>)? (["f","F","d","D"])?
      | "." (["0"-"9"])+ (<EXPONENT>)? (["f","F","d","D"])?
      | (["0"-"9"])+ <EXPONENT> (["f","F","d","D"])?
      | (["0"-"9"])+ (<EXPONENT>)? ["f","F","d","D"]
  >
|
  < #EXPONENT: ["e","E"] (["+","-"])? (["0"-"9"])+ >
|
  < STRING_LITERAL:
      (
      "\""
      (   
        (~["\"","\\","\n","\r","\t","\f","\b"])
        | ("\\" ( ["\\","'","\"","n","r","t","f","b"]) )
        | ("\\" "u" (["0"-"9","a"-"f","A"-"F"]){4} )
      )*
      "\""
      ) | (
      "'"
      (
        (~["'","\\","\n","\r","\t","\f","\b"])
        | ("\\" ( ["\\","'","\"","n","r","t","f","b"]) )
        | ("\\" "u" (["0"-"9","a"-"f","A"-"F"]){4} )
      )*
      "'"
      )
  >
}

TOKEN : /* OPERATORS */
{
  < PLUS: "+">
|
  < MINUS: "-">
|
  < MUL: "*">
|
  < DIV: "/">
|
  < MOD: "%">
|
  < QUESTION: "?">
|
  < COLON: ":">
|
  < COMMA: ",">
|
  < EQ: "==">
|
  < NE: "!=">
|
  < MATCH: "~=">
|
  < LT: "<">
|
  < GT: ">">
|
  < LTE: "<=">
|
  < GTE: ">=">
|
  < LBRAKET: "(">
|
  < RBRAKET: ")">
|
  < LBRACE: "{">
|
  < RBRACE: "}" >
|
  < RIGHT_SHIFT: ">>" >
|
  < URIGHT_SHIFT: ">>>" >
|
  < LEFT_SHIFT: "<<" >
}

TOKEN : /* IDENTIFIERS */
{
  < IDENTIFIER: <LETTER> (<LETTER>|<DIGIT>)* >
|
  < URICHAR: <LETTER> | <DIGIT> | ["/","\\","%","?",":","@","=","#","&","+","$",",","-",".","!","~","*","'","(",")","[","]","}"]>
|
  < #LETTER: ["_","a"-"z","A"-"Z"] >
|
  < #DIGIT: ["0"-"9"] >
}

ASTStart Start() #Start : {}
{
  Expression() ";"
  { return jjtThis; }
}

void Expression() : {}
{
  ConditionalExpression()
}

void ConditionalExpression() : {}
{
  LogicalOrExpression() ( <QUESTION> LogicalOrExpression() <COLON> ConditionalExpression() #ConditionalNode(3) )?
}

void LogicalOrExpression() : {}
{
  LogicalAndExpression() ( <OR> LogicalAndExpression() #LogicalOrNode(2) )*
}

void LogicalAndExpression() : {}
{
  BitwiseOrExpression() ( <AND> BitwiseOrExpression()  #LogicalAndNode(2) )*
}

void BitwiseOrExpression() : {}
{
  BitwiseXorExpression() ( <BITWISE_OR> BitwiseXorExpression() #BitwiseOrNode(2) )*
}

void BitwiseXorExpression() : {}
{
  BitwiseAndExpression() ( <BITWISE_XOR> BitwiseAndExpression() #BitwiseXorNode(2) )*
}

void BitwiseAndExpression() : {}
{
  EqualityExpression() ( <BITWISE_AND> EqualityExpression() #BitwiseAndNode(2) )*
}

void EqualityExpression() #void :
{}
{
  RelationalExpression()
  (
     <EQ> RelationalExpression() #EQNode(2)
   |
     <NE> RelationalExpression() #NENode(2)
   |
     <MATCH> RelationalExpression() #RegexMatchNode(2)
  )*
}
void RelationalExpression() #void :
{}
{
  ShiftExpression()
  (
    <LT> ShiftExpression() #LTNode(2)
   |
    <GT> ShiftExpression() #GTNode(2)
   |
    <LTE> ShiftExpression() #LENode(2)
   |
    <GTE> ShiftExpression() #GENode(2)
  )*
}

void ShiftExpression() #void :
{}
{
  AdditiveExpression()
  (
    <RIGHT_SHIFT> AdditiveExpression() #RightShiftNode(2)
   |
    <URIGHT_SHIFT> AdditiveExpression() #UnsignedRightShiftNode(2)
   |
    <LEFT_SHIFT> AdditiveExpression() #LeftShiftNode(2)
  )*
}

void AdditiveExpression() #void :
{}
{
  MultiplicativeExpression()
  (
    <PLUS> MultiplicativeExpression() #AddNode(2)
   |
    <MINUS> MultiplicativeExpression() #SubtractNode(2)
  )*
}

void MultiplicativeExpression() #void :
{}
{
  UnaryExpression()
  (
    <MUL> UnaryExpression() #MulNode(2)
   |
    <DIV> UnaryExpression() #DivNode(2)
   |
    <MOD> UnaryExpression() #ModNode(2)
  )*
}

void UnaryExpression() : {}
{
  <MINUS> LogicalNotExpression() #UnaryNode(1)
  |
  LogicalNotExpression()
}

void LogicalNotExpression() : {}
{
  <NOT> LogicalNotExpression() #LogicalNotNode(1)
  |
  BitwiseNotExpression()
}

void BitwiseNotExpression() : {}
{
  <BITWISE_NOT> BitwiseNotExpression() #BitwiseNotNode(1)
  |
  PrimaryExpression()
}

void PrimaryExpression() #void :
{ }
{
  Literal()
  |
  Function()
  |
  <LBRAKET> Expression() <RBRAKET>
}


void Function() #FunctionNode :
{}
{
  <IDENTIFIER> Arguments()
}

void Arguments() #void :
{}
{
  <LBRAKET> [ ArgumentList() ] <RBRAKET>
}

void ArgumentList() #void :
{}
{
  Expression() ( <COMMA> Expression() )*
}

void Literal() #void :
{ }
{
 ( <INTEGER_LITERAL> ) #LongConstNode
 |
 ( <FLOATING_POINT_LITERAL> ) #FloatConstNode
 | 
 ( <STRING_LITERAL> ) #StringConstNode
 |
 BooleanLiteral()
 |
 ( <NULL> ) #NullNode
}

void BooleanLiteral() #void :
{}
{
  <TRUE> #TrueNode
|
  <FALSE> #FalseNode
}
```
</details>

<details>

<summary>TestVisitor.java</summary>

```java
public class TestVisitor extends ExpressionParserDefaultVisitor {
  private int indent = 0;
    
  @Override
  public Object defaultVisit(SimpleNode node, Object data) {   
    StringBuilder sb = new StringBuilder(composeIndentation())
            .append(node)
            .append(": ")
            .append(node.jjtGetFirstToken());
    if (node.jjtGetLastToken().image != null && !node.jjtGetLastToken().image.isEmpty()) {
      sb.append("...")
        .append(node.jjtGetLastToken().image);
    }
    
    System.out.println(sb);
    
    indent++;
    node.childrenAccept(this, data);
    indent--;
    return data;
  }
  
  private String composeIndentation()
  {
    StringBuffer sb = new StringBuffer();
    for (int i = 0; i < indent; ++i)
    {
      sb.append(" ");
    }
    return sb.toString();
  }    
}
```
</details>

**Comment by MarcMazas** [comment]
Hi: after just a quick look at the grammar, without doing some tests:
it seems to me that the output is right, and that you are misunderstanding the line
` <PLUS> MultiplicativeExpression() #AddNode(2)`: here I believe the node is created for just `MultiplicativeExpression()`, not for the whole `MultiplicativeExpression()  ( <PLUS> MultiplicativeExpression()`, because there is no closing `)` before the #AddNode(2).

**Comment by Toparvion** [comment]
Hi @MarcMazas, 
Seems you're right as I'm still new to JavaCC and this grammar was produced by another developer quite long ago. Thank you!

I've tried to change:
```diff
--- <PLUS> MultiplicativeExpression() #AddNode(2)
+++ (<PLUS> MultiplicativeExpression()) #AddNode(2)
```
and the output has changed also: 
```diff
--- AddNode: 2...2
+++ AddNode: +...2
```

That's nice! However, this is not what I expected to see. My goal is to get the very first token of the expression in **reading order**, i.e. to get `1` for expression `1+2;` (current change would give me `+` instead).

I cannot simply expand the `#AddNode(2)` scope by putting the parenthesis wider because it would lead to an overlap with `*` modifier's scope.

Could you please suggest a way to achieve this goal?

**Comment by MarcMazas** [comment]
...
```
void AdditiveExpression() #void :
{}
{
  (
    LOOKAHEAD(MultiplicativeExpression() <PLUS>) 
     ( MultiplicativeExpression() <PLUS> MultiplicativeExpression() ) #AddNode(2)
   |
     ( MultiplicativeExpression() <MINUS> MultiplicativeExpression() ) #SubtractNode(2)
  )*
}
```
...
```
void Arguments() #void :
{}
{
  &lt;LBRAKET&gt; ArgumentList() &lt;RBRAKET&gt;
//  &lt;LBRAKET&gt; [ ArgumentList() ] &lt;RBRAKET&gt;
}
```
...

**Comment by Toparvion** [comment]
@MarcMazas , having applied your fix, I got the expected result for expression `1+2;`:
```
Start: 1...;
 AddNode: 1...2          <-- this is what I need
  LongConstNode: 1...1
  LongConstNode: 2...2
```

However, if I append any other arithmetic operation (e.g. `1+2+3;`) I get the following exception:
```
pro.toparvion.sample.javacc.ParseException: Encountered " "+" "+"" at line 1, column 4.

Was expecting one of:

"||" ...
    "&&" ...
    "!" ...
    "|" ...
    "^" ...
    "&" ...
    "~" ...
    "TRUE" ...
    "FALSE" ...
    "NULL" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <STRING_LITERAL> ...
    "-" ...
    "*" ...
    "/" ...
    "%" ...
    "?" ...
    "==" ...
    "!=" ...
    "~=" ...
    "<" ...
    ">" ...
    "<=" ...
    ">=" ...
    "(" ...
    ">>" ...
    ">>>" ...
    "<<" ...
    <IDENTIFIER> ...
    ";" ...
    
	at pro.toparvion.sample.javacc.ExpressionParser.generateParseException(ExpressionParser.java:2108)
	at pro.toparvion.sample.javacc.ExpressionParser.jj_consume_token(ExpressionParser.java:1962)
	at pro.toparvion.sample.javacc.ExpressionParser.Start(ExpressionParser.java:15)
	at pro.toparvion.sample.javacc.Main.main(Main.java:19)
```

Anyway, you've given me a clue with the previous comment, so I think I'll do the rest.

Thank you for the help!

**Comment by MarcMazas** [comment]
```
void AdditiveExpression() #void :
{}
{
    LOOKAHEAD(MultiplicativeExpression() <PLUS>) 
   ( MultiplicativeExpression() ( <PLUS> MultiplicativeExpression() )* ) #AddNode(2)
 |
   ( MultiplicativeExpression() ( <MINUS> MultiplicativeExpression() )* ) #SubtractNode(2)
}

```

**Comment by Toparvion** [comment]
While works fine for the expression above (`1+2+3;`), the new grammar fails to match almost the same expression `1+2-3;` (note the minus sign):
```
pro.toparvion.sample.javacc.ParseException: Encountered " "-" "-"" at line 1, column 7.

Was expecting one of:

"||" ...
    "&&" ...
    "|" ...
    "^" ...
    "&" ...
    "+" ...
    "*" ...
    "/" ...
    "%" ...
    "?" ...
    "==" ...
    "!=" ...
    "~=" ...
    "<" ...
    ">" ...
    "<=" ...
    ">=" ...
    ">>" ...
    ">>>" ...
    "<<" ...
    ";" ...
    
	at pro.toparvion.sample.javacc.ExpressionParser.generateParseException(ExpressionParser.java:2119)
	at pro.toparvion.sample.javacc.ExpressionParser.jj_consume_token(ExpressionParser.java:1973)
	at pro.toparvion.sample.javacc.ExpressionParser.Start(ExpressionParser.java:15)
	at pro.toparvion.sample.javacc.Main.main(Main.java:19)
```
Though the original grammar could parse this expression well.

I suppose this is because the lookahead is specified for addition only (`LOOKAHEAD(MultiplicativeExpression() <PLUS>) `) and thus should be somehow extended/augmented for subtraction as well. I'm going to try it.
Thanks!

P.S. If curious, you can check out this tiny [sample project](https://github.com/Toparvion/javacc-bug-sample) crafted especially for this issue and reproduce the problem in a unit test:
```shell
./mvnw clean generate-sources test
```

**Comment by Toparvion** [comment]
Closing as this is a grammar issue, not the javacc tool itself.
