### ISSUE TITLE
java.lang.IllegalArgumentException when parser used in eclipse

### ISSUE THREAD

**Issue by ramsestom** [javacc/javacc#49]
I am trying to use a javaCC generated parser into a CodenameOne (https://www.codenameone.com/) java application. The proplem I have is that, when I run this app from Eclipse, the parser throw the following error: 
```
java.lang.IllegalArgumentException: [c@550d68db is not a valid WeekDay
	at org.tomlab.mymap.common.openinghours.WeekDayRange.setEndDay(WeekDayRange.java:189)
	at org.tomlab.mymap.common.openinghours.OpeningHoursParser.weekday_range(OpeningHoursParser.java:402)
	at org.tomlab.mymap.common.openinghours.OpeningHoursParser.weekday_selector(OpeningHoursParser.java:480)
	at org.tomlab.mymap.common.openinghours.OpeningHoursParser.rule(OpeningHoursParser.java:988)
	at org.tomlab.mymap.common.openinghours.OpeningHoursParser.rules(OpeningHoursParser.java:1033)
	at org.tomlab.mymap.common.openinghours.OpeningHours.parseOpeningHours(OpeningHours.java:43)
	at org.tomlab.mymap.MyApplication.start(MyApplication.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.codename1.impl.javase.Executor$1$1.run(Executor.java:126)
	at com.codename1.ui.Display.processSerialCalls(Display.java:1130)
	at com.codename1.ui.Display.mainEDTLoop(Display.java:925)
	at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
	at com.codename1.impl.CodenameOneThread.run(CodenameOneThread.java:176)
```
Now, where this is weird is that if I run the exact same application from inside Netbeans, everything works fine! (the parser do not throw any error and the String I am giving it is correctly parsed).
So I don't know why the compiled parser is failing when my app is run from inside Eclipse and not when run from Netbeans...
The value `[c@550d68db` returned in the error log is the value from a String that is supposed to contain the value `Fr` here (So why it contains something that seems to be an object reference in that case is a mystery to me). Do anyone have an idea of what might be the cause of this strange behaviour (the token image to contain what seems to be an object reference rather than the expected value of the token)?
I tried to look at the parser code generated by javaCC to debug but this is too much "obfuscated" to be easily understandable (the jj_consume_token function calls some jj_* functions which are all name coded with numbers or letters). I even don't know exactly how the parser is functioning as in my jj file for example I have some token defined like: 
```
TOKEN :
{
  < WEEKDAY :
    "Mo"
  | "Tu"
  | "We"
  | "Th"
  | "Fr"
  | "Sa"
  | "Su" >
  {
          matchedToken.image = Util.capitalize(image.toString());
  }
| < WEEKDAY3 :
    "Mon"
  | "Tue"
  | "Wed"
  | "Thu"
  | "Fri"
  | "Sat"
  | "Sun" >
  {
          matchedToken.image = Util.capitalize(image.toString()).substring(0, 2);
  }
...
```
but if I look at the parser generated code I can't find the `Fr` or `Fri` Strings (or any other day) anywhere. So how is the parser even knowing which are the possible token values. Do it read it from the jj file at startup each time (but I thought the jj file could be dropped once the parser is generated)? If anyone who knows how javaCC works could enlighten me on this point...

**Comment by ramsestom** [comment]
Fixed. Was actually an issue with codenameone not supporting the full StringBuilder API
