### ISSUE TITLE
javacc-8.0.0: IOException: Invalid template name: /templates/cpp/TokenManagerBoilerPlateMethods.template

### ISSUE THREAD

**Issue by zosrothko** [javacc/javacc#54]
HI

Testing the new javacc-8.0.0 code generator for c++

 ```
FrancisANDRE@DESKTOP-GU149JI /cygdrive/z/git/javacc-8.0/examples/JavaGrammars/cpp
$ make
java -cp ../../../target/javacc.jar jjtree  Java1.1.jjt
Java Compiler Compiler Version 8.0.0 (Tree Builder)
(type "jjtree" with no arguments for help)
Warning: VISITOR_RETURN_TYPE option will be ignored since VISITOR is false
Reading from file Java1.1.jjt . . .
Warning: Output directory "gen" does not exist. Creating the directory.
File "Node.h" does not exist.  Will create one.
File "JavaParserTree.h" does not exist.  Will create one.
File "JavaParserTree.cc" does not exist.  Will create one.
File "JavaParserTreeConstants.h" does not exist.  Will create one.
File "JJTJavaParserState.h" does not exist.  Will create one.
File "JJTJavaParserState.cc" does not exist.  Will create one.
Annotated grammar generated successfully in gen\Java1.1.jj
java -cp ../../../target/javacc.jar javacc  gen/Java1.1.jj
Java Compiler Compiler Version 8.0.0 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file gen/Java1.1.jj . . .
Exception in thread "main" java.io.IOException: Invalid template name: /templates/cpp/TokenManagerBoilerPlateMethods.template
        at org.javacc.utils.OutputFileGenerator.generate(OutputFileGenerator.java:79)
        at org.javacc.parser.LexGen.writeTemplate(LexGen.java:147)
        at org.javacc.parser.LexGenCPP.start(LexGenCPP.java:505)
        at org.javacc.parser.Main.mainProgram(Main.java:295)
        at org.javacc.parser.Main.main(Main.java:153)
        at javacc.main(javacc.java:36)
make: *** [Makefile:13: gen/*.cc] Error 1
 ```

**Comment by kaikalur** [comment]
Are you trying Markus's changes from the csharp_code_generator branch?

**Comment by zosrothko** [comment]
Yes, I am testing the csharp_codegen branch

**Comment by zosrothko** [comment]
Fixed. below the result:
```
FrancisANDRE@DESKTOP-GU149JI /cygdrive/z/git/javacc-8.0/examples/JavaGrammars/cpp
$ ./javaparser.exe ../Test.java
 CompilationUnit
  ImportDeclaration
   Name
  TypeDeclaration
   ClassDeclaration
    UnmodifiedClassDeclaration
     ClassBody
      ClassBodyDeclaration
       MethodDeclaration
        ResultType
        MethodDeclarator
         FormalParameters
          FormalParameter
           Type
            Name
           VariableDeclaratorId
        NameList
         Name
        Block
         BlockStatement
          LocalVariableDeclaration
           Type
            Name
           VariableDeclarator
            VariableDeclaratorId
            VariableInitializer
             Expression
              ConditionalExpression
               ConditionalOrExpression
                ConditionalAndExpression
                 InclusiveOrExpression
                  ExclusiveOrExpression
                   AndExpression
                    EqualityExpression
                     InstanceOfExpression
                      RelationalExpression
                       ShiftExpression
                        AdditiveExpression
                         MultiplicativeExpression
                          UnaryExpression
                           UnaryExpressionNotPlusMinus
                            PostfixExpression
                             PrimaryExpression
                              PrimaryPrefix
                               Literal
                                NullLiteral
         BlockStatement
          Statement
           IfStatement
            Expression
             ConditionalExpression
              ConditionalOrExpression
               ConditionalAndExpression
                InclusiveOrExpression
                 ExclusiveOrExpression
                  AndExpression
                   EqualityExpression
                    InstanceOfExpression
                     RelationalExpression
                      ShiftExpression
                       AdditiveExpression
                        MultiplicativeExpression
                         UnaryExpression
                          UnaryExpressionNotPlusMinus
                           PostfixExpression
                            PrimaryExpression
                             PrimaryPrefix
                              Name
                    InstanceOfExpression
                     RelationalExpression
                      ShiftExpression
                       AdditiveExpression
                        MultiplicativeExpression
                         UnaryExpression
                          UnaryExpressionNotPlusMinus
                           PostfixExpression
                            PrimaryExpression
                             PrimaryPrefix
                              Literal
            Statement
             StatementExpression
              PrimaryExpression
               PrimaryPrefix
                Name
              AssignmentOperator
              Expression
               ConditionalExpression
                ConditionalOrExpression
                 ConditionalAndExpression
                  InclusiveOrExpression
                   ExclusiveOrExpression
                    AndExpression
                     EqualityExpression
                      InstanceOfExpression
                       RelationalExpression
                        ShiftExpression
                         AdditiveExpression
                          MultiplicativeExpression
                           UnaryExpression
                            UnaryExpressionNotPlusMinus
                             PostfixExpression
                              PrimaryExpression
                               PrimaryPrefix
                                AllocationExpression
                                 Name
                                 Arguments
                                  ArgumentList
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     AllocationExpression
                                                      Name
                                                      Arguments
                                                       ArgumentList
                                                        Expression
                                                         ConditionalExpression
                                                          ConditionalOrExpression
                                                           ConditionalAndExpression
                                                            InclusiveOrExpression
                                                             ExclusiveOrExpression
                                                              AndExpression
                                                               EqualityExpression
                                                                InstanceOfExpression
                                                                 RelationalExpression
                                                                  ShiftExpression
                                                                   AdditiveExpression
                                                                    MultiplicativeExpression
                                                                     UnaryExpression
                                                                      UnaryExpressionNotPlusMinus
                                                                       PostfixExpression
                                                                        PrimaryExpression
                                                                         PrimaryPrefix
                                                                          AllocationExpression
                                                                           Name
                                                                           Arguments
                                                                            ArgumentList
                                                                             Expression
                                                                              ConditionalExpression
                                                                               ConditionalOrExpression
                                                                                ConditionalAndExpression
                                                                                 InclusiveOrExpression
                                                                                  ExclusiveOrExpression
                                                                                   AndExpression
                                                                                    EqualityExpression
                                                                                     InstanceOfExpression
                                                                                      RelationalExpression
                                                                                       ShiftExpression
                                                                                        AdditiveExpression
                                                                                         MultiplicativeExpression
                                                                                          UnaryExpression
                                                                                           UnaryExpressionNotPlusMinus
                                                                                            PostfixExpression
                                                                                             PrimaryExpression
                                                                                              PrimaryPrefix
                                                                                               Name
                                                                                              PrimarySuffix
                                                                                               Expression
                                                                                                ConditionalExpression
                                                                                                 ConditionalOrExpression
                                                                                                  ConditionalAndExpression
                                                                                                   InclusiveOrExpression
                                                                                                    ExclusiveOrExpression
                                                                                                     AndExpression
                                                                                                      EqualityExpression
                                                                                                       InstanceOfExpression
                                                                                                        RelationalExpression
                                                                                                         ShiftExpression
                                                                                                          AdditiveExpression
                                                                                                           MultiplicativeExpression
                                                                                                            UnaryExpression
                                                                                                             UnaryExpressionNotPlusMinus
                                                                                                              PostfixExpression
                                                                                                               PrimaryExpression
                                                                                                                PrimaryPrefix
                                                                                                                 Literal
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     Name
                                                    PrimarySuffix
                                                     Expression
                                                      ConditionalExpression
                                                       ConditionalOrExpression
                                                        ConditionalAndExpression
                                                         InclusiveOrExpression
                                                          ExclusiveOrExpression
                                                           AndExpression
                                                            EqualityExpression
                                                             InstanceOfExpression
                                                              RelationalExpression
                                                               ShiftExpression
                                                                AdditiveExpression
                                                                 MultiplicativeExpression
                                                                  UnaryExpression
                                                                   UnaryExpressionNotPlusMinus
                                                                    PostfixExpression
                                                                     PrimaryExpression
                                                                      PrimaryPrefix
                                                                       Literal
            Statement
             StatementExpression
              PrimaryExpression
               PrimaryPrefix
                Name
              AssignmentOperator
              Expression
               ConditionalExpression
                ConditionalOrExpression
                 ConditionalAndExpression
                  InclusiveOrExpression
                   ExclusiveOrExpression
                    AndExpression
                     EqualityExpression
                      InstanceOfExpression
                       RelationalExpression
                        ShiftExpression
                         AdditiveExpression
                          MultiplicativeExpression
                           UnaryExpression
                            UnaryExpressionNotPlusMinus
                             PostfixExpression
                              PrimaryExpression
                               PrimaryPrefix
                                AllocationExpression
                                 Name
                                 Arguments
                                  ArgumentList
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     AllocationExpression
                                                      Name
                                                      Arguments
                                                       ArgumentList
                                                        Expression
                                                         ConditionalExpression
                                                          ConditionalOrExpression
                                                           ConditionalAndExpression
                                                            InclusiveOrExpression
                                                             ExclusiveOrExpression
                                                              AndExpression
                                                               EqualityExpression
                                                                InstanceOfExpression
                                                                 RelationalExpression
                                                                  ShiftExpression
                                                                   AdditiveExpression
                                                                    MultiplicativeExpression
                                                                     UnaryExpression
                                                                      UnaryExpressionNotPlusMinus
                                                                       PostfixExpression
                                                                        PrimaryExpression
                                                                         PrimaryPrefix
                                                                          AllocationExpression
                                                                           Name
                                                                           Arguments
                                                                            ArgumentList
                                                                             Expression
                                                                              ConditionalExpression
                                                                               ConditionalOrExpression
                                                                                ConditionalAndExpression
                                                                                 InclusiveOrExpression
                                                                                  ExclusiveOrExpression
                                                                                   AndExpression
                                                                                    EqualityExpression
                                                                                     InstanceOfExpression
                                                                                      RelationalExpression
                                                                                       ShiftExpression
                                                                                        AdditiveExpression
                                                                                         MultiplicativeExpression
                                                                                          UnaryExpression
                                                                                           UnaryExpressionNotPlusMinus
                                                                                            PostfixExpression
                                                                                             PrimaryExpression
                                                                                              PrimaryPrefix
                                                                                               Name
                                                                                              PrimarySuffix
                                                                                               Expression
                                                                                                ConditionalExpression
                                                                                                 ConditionalOrExpression
                                                                                                  ConditionalAndExpression
                                                                                                   InclusiveOrExpression
                                                                                                    ExclusiveOrExpression
                                                                                                     AndExpression
                                                                                                      EqualityExpression
                                                                                                       InstanceOfExpression
                                                                                                        RelationalExpression
                                                                                                         ShiftExpression
                                                                                                          AdditiveExpression
                                                                                                           MultiplicativeExpression
                                                                                                            UnaryExpression
                                                                                                             UnaryExpressionNotPlusMinus
                                                                                                              PostfixExpression
                                                                                                               PrimaryExpression
                                                                                                                PrimaryPrefix
                                                                                                                 Literal
         BlockStatement
          LocalVariableDeclaration
           Type
            Name
           VariableDeclarator
            VariableDeclaratorId
            VariableInitializer
             Expression
              ConditionalExpression
               ConditionalOrExpression
                ConditionalAndExpression
                 InclusiveOrExpression
                  ExclusiveOrExpression
                   AndExpression
                    EqualityExpression
                     InstanceOfExpression
                      RelationalExpression
                       ShiftExpression
                        AdditiveExpression
                         MultiplicativeExpression
                          UnaryExpression
                           UnaryExpressionNotPlusMinus
                            PostfixExpression
                             PrimaryExpression
                              PrimaryPrefix
                               AllocationExpression
                                Name
                                Arguments
                                 ArgumentList
                                  Expression
                                   ConditionalExpression
                                    ConditionalOrExpression
                                     ConditionalAndExpression
                                      InclusiveOrExpression
                                       ExclusiveOrExpression
                                        AndExpression
                                         EqualityExpression
                                          InstanceOfExpression
                                           RelationalExpression
                                            ShiftExpression
                                             AdditiveExpression
                                              MultiplicativeExpression
                                               UnaryExpression
                                                UnaryExpressionNotPlusMinus
                                                 PostfixExpression
                                                  PrimaryExpression
                                                   PrimaryPrefix
                                                    Name
         BlockStatement
          Statement
           StatementExpression
            PrimaryExpression
             PrimaryPrefix
              Name
             PrimarySuffix
              Arguments


FrancisANDRE@DESKTOP-GU149JI /cygdrive/z/git/javacc-8.0/examples/JavaGrammars/cpp
```

**Comment by zosrothko** [comment]
Works also with wjavaparser.exe
```
FrancisANDRE@DESKTOP-GU149JI /cygdrive/z/git/javacc-8.0/examples/JavaGrammars/cpp
$ ./wjavaparser.exe ../Test.java
 CompilationUnit
  ImportDeclaration
   Name
  TypeDeclaration
   ClassDeclaration
    UnmodifiedClassDeclaration
     ClassBody
      ClassBodyDeclaration
       MethodDeclaration
        ResultType
        MethodDeclarator
         FormalParameters
          FormalParameter
           Type
            Name
           VariableDeclaratorId
        NameList
         Name
        Block
         BlockStatement
          LocalVariableDeclaration
           Type
            Name
           VariableDeclarator
            VariableDeclaratorId
            VariableInitializer
             Expression
              ConditionalExpression
               ConditionalOrExpression
                ConditionalAndExpression
                 InclusiveOrExpression
                  ExclusiveOrExpression
                   AndExpression
                    EqualityExpression
                     InstanceOfExpression
                      RelationalExpression
                       ShiftExpression
                        AdditiveExpression
                         MultiplicativeExpression
                          UnaryExpression
                           UnaryExpressionNotPlusMinus
                            PostfixExpression
                             PrimaryExpression
                              PrimaryPrefix
                               Literal
                                NullLiteral
         BlockStatement
          Statement
           IfStatement
            Expression
             ConditionalExpression
              ConditionalOrExpression
               ConditionalAndExpression
                InclusiveOrExpression
                 ExclusiveOrExpression
                  AndExpression
                   EqualityExpression
                    InstanceOfExpression
                     RelationalExpression
                      ShiftExpression
                       AdditiveExpression
                        MultiplicativeExpression
                         UnaryExpression
                          UnaryExpressionNotPlusMinus
                           PostfixExpression
                            PrimaryExpression
                             PrimaryPrefix
                              Name
                    InstanceOfExpression
                     RelationalExpression
                      ShiftExpression
                       AdditiveExpression
                        MultiplicativeExpression
                         UnaryExpression
                          UnaryExpressionNotPlusMinus
                           PostfixExpression
                            PrimaryExpression
                             PrimaryPrefix
                              Literal
            Statement
             StatementExpression
              PrimaryExpression
               PrimaryPrefix
                Name
              AssignmentOperator
              Expression
               ConditionalExpression
                ConditionalOrExpression
                 ConditionalAndExpression
                  InclusiveOrExpression
                   ExclusiveOrExpression
                    AndExpression
                     EqualityExpression
                      InstanceOfExpression
                       RelationalExpression
                        ShiftExpression
                         AdditiveExpression
                          MultiplicativeExpression
                           UnaryExpression
                            UnaryExpressionNotPlusMinus
                             PostfixExpression
                              PrimaryExpression
                               PrimaryPrefix
                                AllocationExpression
                                 Name
                                 Arguments
                                  ArgumentList
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     AllocationExpression
                                                      Name
                                                      Arguments
                                                       ArgumentList
                                                        Expression
                                                         ConditionalExpression
                                                          ConditionalOrExpression
                                                           ConditionalAndExpression
                                                            InclusiveOrExpression
                                                             ExclusiveOrExpression
                                                              AndExpression
                                                               EqualityExpression
                                                                InstanceOfExpression
                                                                 RelationalExpression
                                                                  ShiftExpression
                                                                   AdditiveExpression
                                                                    MultiplicativeExpression
                                                                     UnaryExpression
                                                                      UnaryExpressionNotPlusMinus
                                                                       PostfixExpression
                                                                        PrimaryExpression
                                                                         PrimaryPrefix
                                                                          AllocationExpression
                                                                           Name
                                                                           Arguments
                                                                            ArgumentList
                                                                             Expression
                                                                              ConditionalExpression
                                                                               ConditionalOrExpression
                                                                                ConditionalAndExpression
                                                                                 InclusiveOrExpression
                                                                                  ExclusiveOrExpression
                                                                                   AndExpression
                                                                                    EqualityExpression
                                                                                     InstanceOfExpression
                                                                                      RelationalExpression
                                                                                       ShiftExpression
                                                                                        AdditiveExpression
                                                                                         MultiplicativeExpression
                                                                                          UnaryExpression
                                                                                           UnaryExpressionNotPlusMinus
                                                                                            PostfixExpression
                                                                                             PrimaryExpression
                                                                                              PrimaryPrefix
                                                                                               Name
                                                                                              PrimarySuffix
                                                                                               Expression
                                                                                                ConditionalExpression
                                                                                                 ConditionalOrExpression
                                                                                                  ConditionalAndExpression
                                                                                                   InclusiveOrExpression
                                                                                                    ExclusiveOrExpression
                                                                                                     AndExpression
                                                                                                      EqualityExpression
                                                                                                       InstanceOfExpression
                                                                                                        RelationalExpression
                                                                                                         ShiftExpression
                                                                                                          AdditiveExpression
                                                                                                           MultiplicativeExpression
                                                                                                            UnaryExpression
                                                                                                             UnaryExpressionNotPlusMinus
                                                                                                              PostfixExpression
                                                                                                               PrimaryExpression
                                                                                                                PrimaryPrefix
                                                                                                                 Literal
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     Name
                                                    PrimarySuffix
                                                     Expression
                                                      ConditionalExpression
                                                       ConditionalOrExpression
                                                        ConditionalAndExpression
                                                         InclusiveOrExpression
                                                          ExclusiveOrExpression
                                                           AndExpression
                                                            EqualityExpression
                                                             InstanceOfExpression
                                                              RelationalExpression
                                                               ShiftExpression
                                                                AdditiveExpression
                                                                 MultiplicativeExpression
                                                                  UnaryExpression
                                                                   UnaryExpressionNotPlusMinus
                                                                    PostfixExpression
                                                                     PrimaryExpression
                                                                      PrimaryPrefix
                                                                       Literal
            Statement
             StatementExpression
              PrimaryExpression
               PrimaryPrefix
                Name
              AssignmentOperator
              Expression
               ConditionalExpression
                ConditionalOrExpression
                 ConditionalAndExpression
                  InclusiveOrExpression
                   ExclusiveOrExpression
                    AndExpression
                     EqualityExpression
                      InstanceOfExpression
                       RelationalExpression
                        ShiftExpression
                         AdditiveExpression
                          MultiplicativeExpression
                           UnaryExpression
                            UnaryExpressionNotPlusMinus
                             PostfixExpression
                              PrimaryExpression
                               PrimaryPrefix
                                AllocationExpression
                                 Name
                                 Arguments
                                  ArgumentList
                                   Expression
                                    ConditionalExpression
                                     ConditionalOrExpression
                                      ConditionalAndExpression
                                       InclusiveOrExpression
                                        ExclusiveOrExpression
                                         AndExpression
                                          EqualityExpression
                                           InstanceOfExpression
                                            RelationalExpression
                                             ShiftExpression
                                              AdditiveExpression
                                               MultiplicativeExpression
                                                UnaryExpression
                                                 UnaryExpressionNotPlusMinus
                                                  PostfixExpression
                                                   PrimaryExpression
                                                    PrimaryPrefix
                                                     AllocationExpression
                                                      Name
                                                      Arguments
                                                       ArgumentList
                                                        Expression
                                                         ConditionalExpression
                                                          ConditionalOrExpression
                                                           ConditionalAndExpression
                                                            InclusiveOrExpression
                                                             ExclusiveOrExpression
                                                              AndExpression
                                                               EqualityExpression
                                                                InstanceOfExpression
                                                                 RelationalExpression
                                                                  ShiftExpression
                                                                   AdditiveExpression
                                                                    MultiplicativeExpression
                                                                     UnaryExpression
                                                                      UnaryExpressionNotPlusMinus
                                                                       PostfixExpression
                                                                        PrimaryExpression
                                                                         PrimaryPrefix
                                                                          AllocationExpression
                                                                           Name
                                                                           Arguments
                                                                            ArgumentList
                                                                             Expression
                                                                              ConditionalExpression
                                                                               ConditionalOrExpression
                                                                                ConditionalAndExpression
                                                                                 InclusiveOrExpression
                                                                                  ExclusiveOrExpression
                                                                                   AndExpression
                                                                                    EqualityExpression
                                                                                     InstanceOfExpression
                                                                                      RelationalExpression
                                                                                       ShiftExpression
                                                                                        AdditiveExpression
                                                                                         MultiplicativeExpression
                                                                                          UnaryExpression
                                                                                           UnaryExpressionNotPlusMinus
                                                                                            PostfixExpression
                                                                                             PrimaryExpression
                                                                                              PrimaryPrefix
                                                                                               Name
                                                                                              PrimarySuffix
                                                                                               Expression
                                                                                                ConditionalExpression
                                                                                                 ConditionalOrExpression
                                                                                                  ConditionalAndExpression
                                                                                                   InclusiveOrExpression
                                                                                                    ExclusiveOrExpression
                                                                                                     AndExpression
                                                                                                      EqualityExpression
                                                                                                       InstanceOfExpression
                                                                                                        RelationalExpression
                                                                                                         ShiftExpression
                                                                                                          AdditiveExpression
                                                                                                           MultiplicativeExpression
                                                                                                            UnaryExpression
                                                                                                             UnaryExpressionNotPlusMinus
                                                                                                              PostfixExpression
                                                                                                               PrimaryExpression
                                                                                                                PrimaryPrefix
                                                                                                                 Literal
         BlockStatement
          LocalVariableDeclaration
           Type
            Name
           VariableDeclarator
            VariableDeclaratorId
            VariableInitializer
             Expression
              ConditionalExpression
               ConditionalOrExpression
                ConditionalAndExpression
                 InclusiveOrExpression
                  ExclusiveOrExpression
                   AndExpression
                    EqualityExpression
                     InstanceOfExpression
                      RelationalExpression
                       ShiftExpression
                        AdditiveExpression
                         MultiplicativeExpression
                          UnaryExpression
                           UnaryExpressionNotPlusMinus
                            PostfixExpression
                             PrimaryExpression
                              PrimaryPrefix
                               AllocationExpression
                                Name
                                Arguments
                                 ArgumentList
                                  Expression
                                   ConditionalExpression
                                    ConditionalOrExpression
                                     ConditionalAndExpression
                                      InclusiveOrExpression
                                       ExclusiveOrExpression
                                        AndExpression
                                         EqualityExpression
                                          InstanceOfExpression
                                           RelationalExpression
                                            ShiftExpression
                                             AdditiveExpression
                                              MultiplicativeExpression
                                               UnaryExpression
                                                UnaryExpressionNotPlusMinus
                                                 PostfixExpression
                                                  PrimaryExpression
                                                   PrimaryPrefix
                                                    Name
         BlockStatement
          Statement
           StatementExpression
            PrimaryExpression
             PrimaryPrefix
              Name
             PrimarySuffix
              Arguments

FrancisANDRE@DESKTOP-GU149JI /cygdrive/z/git/javacc-8.0/examples/JavaGrammars/cpp
```
