### ISSUE TITLE
JavaCC 8.0.0: NPE at org.javacc.cpp.todo.NfaState.DumpMoveNfa(NfaState.java:2818)

### ISSUE THREAD

**Issue by zosrothko** [javacc/javacc#61]
Hi

With latest JavaCC 8.0.0, one got
```
Z:\git\asn1cpp\code\ASN1Parser>java -cp z:\git\javacc-8.0\target\javacc.jar javacc
Java Compiler Compiler Version 8.0.0 (Parser Generator)

Z:\git\asn1cpp\code\ASN1Parser>java -cp z:\git\javacc-8.0\target\javacc.jar;Z:\git\javacc-8.0\codegenerator\cpp\cpp-codegenerator.jar javacc -output_directory=gen Parser.jj
Java Compiler Compiler Version 8.0.0 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file Parser.jj . . .
Warning: Output directory "gen" does not exist. Creating the directory.
Exception in thread "main" java.lang.NullPointerException
        at org.javacc.cpp.todo.NfaState.DumpMoveNfa(NfaState.java:2818)
        at org.javacc.cpp.TokenManagerCodeGenerator.generateCode(TokenManagerCodeGenerator.java:260)
        at org.javacc.parser.LexGen.start(LexGen.java:608)
        at org.javacc.parser.Main.mainProgram(Main.java:266)
        at org.javacc.parser.Main.main(Main.java:153)
        at javacc.main(javacc.java:36)
```

**Comment by mbrigl** [comment]
Where can I find asn1cpp\code\ASN1Parser\Parser.jj?

**Comment by mbrigl** [comment]
All of the jj files in _grammars_ have Java Code Production and don't work for C++

**Comment by new-javacc** [comment]
Your can try the grammar repository:https://javacc.org/grammar-libraryOn Sep 17, 2018 12:33 PM, Markus Brigl <notifications@github.com> wrote:All of the jj files in grammars have Java Code Production and don't work for C++
