### ISSUE TITLE
JavaCC parser fails on try no catch nor finally

### ISSUE THREAD

**Issue by MarcMazas** [javacc/javacc#81]
Hi
a try / catch / finally  must contain at least on catch or one finally but JavaCC fails with a NPE after the error message
grammar .jj: 
void ko2() :{}{
  try { "C" }
}
Output:
     [java] Java Compiler Compiler Version 7.0.0 (Parser Generator)
     [java] Warning: Line 10, Column 3: Command line setting of "OUTPUT_DIRECTORY" modifies option value in file.(type "javacc" with no arguments for help)
     [java] Reading from file D:\Devs\GitRepo\jtb\src\test\jj/grammars/j/TinyGrammar.jj . . .
     [java] Error: Line 493, Column 3: Try block must contain at least one catch or finally block.
     [java] Exception in thread "main" java.lang.NullPointerException
     [java] 	at org.javacc.parser.JavaCCParser.expansion(JavaCCParser.java:833)
     [java] 	at org.javacc.parser.JavaCCParser.expansion_choices(JavaCCParser.java:773)
     [java] 	at org.javacc.parser.JavaCCParser.bnf_production(JavaCCParser.java:550)
     [java] 	at org.javacc.parser.JavaCCParser.production(JavaCCParser.java:404)
     [java] 	at org.javacc.parser.JavaCCParser.javacc_input(JavaCCParser.java:229)
     [java] 	at org.javacc.parser.Main.mainProgram(Main.java:218)
     [java] 	at org.javacc.parser.Main.main(Main.java:154)

**Comment by MarcMazas** [comment]
Fix is simple:
in 
void Expansion(Container c1) :
...
  ( LOOKAHEAD(0, { notTailOfExpansionUnit() } )
    expansion_unit(c2)
      if (c2.member != null) { // fix
	{
	  seq.units.add(c2.member);
	  ((Expansion)c2.member).parent = seq;
	  ((Expansion)c2.member).ordinal = seq.units.size()-1;
	}
} // fix
  )+
...

**Comment by MarcMazas** [comment]
Ok, looks to have been fixed between versions 7.0.0 & 7.0.4.
